// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: sec0.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Status, statusFromJSON, statusToJSON } from "./constants";

export const protobufPackage = "";

/** A message must be of type Cmd or Resp */
export enum Sec0MsgType {
  S0_Session_Command = 0,
  S0_Session_Response = 1,
  UNRECOGNIZED = -1,
}

export function sec0MsgTypeFromJSON(object: any): Sec0MsgType {
  switch (object) {
    case 0:
    case "S0_Session_Command":
      return Sec0MsgType.S0_Session_Command;
    case 1:
    case "S0_Session_Response":
      return Sec0MsgType.S0_Session_Response;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Sec0MsgType.UNRECOGNIZED;
  }
}

export function sec0MsgTypeToJSON(object: Sec0MsgType): string {
  switch (object) {
    case Sec0MsgType.S0_Session_Command:
      return "S0_Session_Command";
    case Sec0MsgType.S0_Session_Response:
      return "S0_Session_Response";
    case Sec0MsgType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Data structure of Session command/request packet */
export interface S0SessionCmd {
}

/** Data structure of Session response packet */
export interface S0SessionResp {
  status: Status;
}

/** Payload structure of session data */
export interface Sec0Payload {
  /** !< Type of message */
  msg: Sec0MsgType;
  /** !< Payload data interpreted as Cmd */
  sc?:
    | S0SessionCmd
    | undefined;
  /** !< Payload data interpreted as Resp */
  sr?: S0SessionResp | undefined;
}

function createBaseS0SessionCmd(): S0SessionCmd {
  return {};
}

export const S0SessionCmd: MessageFns<S0SessionCmd> = {
  encode(_: S0SessionCmd, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): S0SessionCmd {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseS0SessionCmd();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): S0SessionCmd {
    return {};
  },

  toJSON(_: S0SessionCmd): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<S0SessionCmd>, I>>(base?: I): S0SessionCmd {
    return S0SessionCmd.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<S0SessionCmd>, I>>(_: I): S0SessionCmd {
    const message = createBaseS0SessionCmd();
    return message;
  },
};

function createBaseS0SessionResp(): S0SessionResp {
  return { status: 0 };
}

export const S0SessionResp: MessageFns<S0SessionResp> = {
  encode(message: S0SessionResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== 0) {
      writer.uint32(8).int32(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): S0SessionResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseS0SessionResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): S0SessionResp {
    return { status: isSet(object.status) ? statusFromJSON(object.status) : 0 };
  },

  toJSON(message: S0SessionResp): unknown {
    const obj: any = {};
    if (message.status !== 0) {
      obj.status = statusToJSON(message.status);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<S0SessionResp>, I>>(base?: I): S0SessionResp {
    return S0SessionResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<S0SessionResp>, I>>(object: I): S0SessionResp {
    const message = createBaseS0SessionResp();
    message.status = object.status ?? 0;
    return message;
  },
};

function createBaseSec0Payload(): Sec0Payload {
  return { msg: 0, sc: undefined, sr: undefined };
}

export const Sec0Payload: MessageFns<Sec0Payload> = {
  encode(message: Sec0Payload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.msg !== 0) {
      writer.uint32(8).int32(message.msg);
    }
    if (message.sc !== undefined) {
      S0SessionCmd.encode(message.sc, writer.uint32(162).fork()).join();
    }
    if (message.sr !== undefined) {
      S0SessionResp.encode(message.sr, writer.uint32(170).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Sec0Payload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSec0Payload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.msg = reader.int32() as any;
          continue;
        }
        case 20: {
          if (tag !== 162) {
            break;
          }

          message.sc = S0SessionCmd.decode(reader, reader.uint32());
          continue;
        }
        case 21: {
          if (tag !== 170) {
            break;
          }

          message.sr = S0SessionResp.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Sec0Payload {
    return {
      msg: isSet(object.msg) ? sec0MsgTypeFromJSON(object.msg) : 0,
      sc: isSet(object.sc) ? S0SessionCmd.fromJSON(object.sc) : undefined,
      sr: isSet(object.sr) ? S0SessionResp.fromJSON(object.sr) : undefined,
    };
  },

  toJSON(message: Sec0Payload): unknown {
    const obj: any = {};
    if (message.msg !== 0) {
      obj.msg = sec0MsgTypeToJSON(message.msg);
    }
    if (message.sc !== undefined) {
      obj.sc = S0SessionCmd.toJSON(message.sc);
    }
    if (message.sr !== undefined) {
      obj.sr = S0SessionResp.toJSON(message.sr);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Sec0Payload>, I>>(base?: I): Sec0Payload {
    return Sec0Payload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Sec0Payload>, I>>(object: I): Sec0Payload {
    const message = createBaseSec0Payload();
    message.msg = object.msg ?? 0;
    message.sc = (object.sc !== undefined && object.sc !== null) ? S0SessionCmd.fromPartial(object.sc) : undefined;
    message.sr = (object.sr !== undefined && object.sr !== null) ? S0SessionResp.fromPartial(object.sr) : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
