// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: sec1.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Status, statusFromJSON, statusToJSON } from "./constants";

export const protobufPackage = "";

/** A message must be of type Cmd0 / Cmd1 / Resp0 / Resp1 */
export enum Sec1MsgType {
  Session_Command0 = 0,
  Session_Response0 = 1,
  Session_Command1 = 2,
  Session_Response1 = 3,
  UNRECOGNIZED = -1,
}

export function sec1MsgTypeFromJSON(object: any): Sec1MsgType {
  switch (object) {
    case 0:
    case "Session_Command0":
      return Sec1MsgType.Session_Command0;
    case 1:
    case "Session_Response0":
      return Sec1MsgType.Session_Response0;
    case 2:
    case "Session_Command1":
      return Sec1MsgType.Session_Command1;
    case 3:
    case "Session_Response1":
      return Sec1MsgType.Session_Response1;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Sec1MsgType.UNRECOGNIZED;
  }
}

export function sec1MsgTypeToJSON(object: Sec1MsgType): string {
  switch (object) {
    case Sec1MsgType.Session_Command0:
      return "Session_Command0";
    case Sec1MsgType.Session_Response0:
      return "Session_Response0";
    case Sec1MsgType.Session_Command1:
      return "Session_Command1";
    case Sec1MsgType.Session_Response1:
      return "Session_Response1";
    case Sec1MsgType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Data structure of Session command1 packet */
export interface SessionCmd1 {
  clientVerifyData: Uint8Array;
}

/** Data structure of Session response1 packet */
export interface SessionResp1 {
  status: Status;
  deviceVerifyData: Uint8Array;
}

/** Data structure of Session command0 packet */
export interface SessionCmd0 {
  clientPubkey: Uint8Array;
}

/** Data structure of Session response0 packet */
export interface SessionResp0 {
  status: Status;
  devicePubkey: Uint8Array;
  deviceRandom: Uint8Array;
}

/** Payload structure of session data */
export interface Sec1Payload {
  /** !< Type of message */
  msg: Sec1MsgType;
  /** !< Payload data interpreted as Cmd0 */
  sc0?:
    | SessionCmd0
    | undefined;
  /** !< Payload data interpreted as Resp0 */
  sr0?:
    | SessionResp0
    | undefined;
  /** !< Payload data interpreted as Cmd1 */
  sc1?:
    | SessionCmd1
    | undefined;
  /** !< Payload data interpreted as Resp1 */
  sr1?: SessionResp1 | undefined;
}

function createBaseSessionCmd1(): SessionCmd1 {
  return { clientVerifyData: new Uint8Array(0) };
}

export const SessionCmd1: MessageFns<SessionCmd1> = {
  encode(message: SessionCmd1, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clientVerifyData.length !== 0) {
      writer.uint32(18).bytes(message.clientVerifyData);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionCmd1 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionCmd1();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clientVerifyData = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SessionCmd1 {
    return {
      clientVerifyData: isSet(object.clientVerifyData)
        ? bytesFromBase64(object.clientVerifyData)
        : isSet(object.client_verify_data)
        ? bytesFromBase64(object.client_verify_data)
        : new Uint8Array(0),
    };
  },

  toJSON(message: SessionCmd1): unknown {
    const obj: any = {};
    if (message.clientVerifyData.length !== 0) {
      obj.clientVerifyData = base64FromBytes(message.clientVerifyData);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SessionCmd1>, I>>(base?: I): SessionCmd1 {
    return SessionCmd1.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SessionCmd1>, I>>(object: I): SessionCmd1 {
    const message = createBaseSessionCmd1();
    message.clientVerifyData = object.clientVerifyData ?? new Uint8Array(0);
    return message;
  },
};

function createBaseSessionResp1(): SessionResp1 {
  return { status: 0, deviceVerifyData: new Uint8Array(0) };
}

export const SessionResp1: MessageFns<SessionResp1> = {
  encode(message: SessionResp1, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== 0) {
      writer.uint32(8).int32(message.status);
    }
    if (message.deviceVerifyData.length !== 0) {
      writer.uint32(26).bytes(message.deviceVerifyData);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionResp1 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionResp1();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.deviceVerifyData = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SessionResp1 {
    return {
      status: isSet(object.status) ? statusFromJSON(object.status) : 0,
      deviceVerifyData: isSet(object.deviceVerifyData)
        ? bytesFromBase64(object.deviceVerifyData)
        : isSet(object.device_verify_data)
        ? bytesFromBase64(object.device_verify_data)
        : new Uint8Array(0),
    };
  },

  toJSON(message: SessionResp1): unknown {
    const obj: any = {};
    if (message.status !== 0) {
      obj.status = statusToJSON(message.status);
    }
    if (message.deviceVerifyData.length !== 0) {
      obj.deviceVerifyData = base64FromBytes(message.deviceVerifyData);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SessionResp1>, I>>(base?: I): SessionResp1 {
    return SessionResp1.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SessionResp1>, I>>(object: I): SessionResp1 {
    const message = createBaseSessionResp1();
    message.status = object.status ?? 0;
    message.deviceVerifyData = object.deviceVerifyData ?? new Uint8Array(0);
    return message;
  },
};

function createBaseSessionCmd0(): SessionCmd0 {
  return { clientPubkey: new Uint8Array(0) };
}

export const SessionCmd0: MessageFns<SessionCmd0> = {
  encode(message: SessionCmd0, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clientPubkey.length !== 0) {
      writer.uint32(10).bytes(message.clientPubkey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionCmd0 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionCmd0();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clientPubkey = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SessionCmd0 {
    return {
      clientPubkey: isSet(object.clientPubkey)
        ? bytesFromBase64(object.clientPubkey)
        : isSet(object.client_pubkey)
        ? bytesFromBase64(object.client_pubkey)
        : new Uint8Array(0),
    };
  },

  toJSON(message: SessionCmd0): unknown {
    const obj: any = {};
    if (message.clientPubkey.length !== 0) {
      obj.clientPubkey = base64FromBytes(message.clientPubkey);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SessionCmd0>, I>>(base?: I): SessionCmd0 {
    return SessionCmd0.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SessionCmd0>, I>>(object: I): SessionCmd0 {
    const message = createBaseSessionCmd0();
    message.clientPubkey = object.clientPubkey ?? new Uint8Array(0);
    return message;
  },
};

function createBaseSessionResp0(): SessionResp0 {
  return { status: 0, devicePubkey: new Uint8Array(0), deviceRandom: new Uint8Array(0) };
}

export const SessionResp0: MessageFns<SessionResp0> = {
  encode(message: SessionResp0, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== 0) {
      writer.uint32(8).int32(message.status);
    }
    if (message.devicePubkey.length !== 0) {
      writer.uint32(18).bytes(message.devicePubkey);
    }
    if (message.deviceRandom.length !== 0) {
      writer.uint32(26).bytes(message.deviceRandom);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionResp0 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionResp0();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.devicePubkey = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.deviceRandom = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SessionResp0 {
    return {
      status: isSet(object.status) ? statusFromJSON(object.status) : 0,
      devicePubkey: isSet(object.devicePubkey)
        ? bytesFromBase64(object.devicePubkey)
        : isSet(object.device_pubkey)
        ? bytesFromBase64(object.device_pubkey)
        : new Uint8Array(0),
      deviceRandom: isSet(object.deviceRandom)
        ? bytesFromBase64(object.deviceRandom)
        : isSet(object.device_random)
        ? bytesFromBase64(object.device_random)
        : new Uint8Array(0),
    };
  },

  toJSON(message: SessionResp0): unknown {
    const obj: any = {};
    if (message.status !== 0) {
      obj.status = statusToJSON(message.status);
    }
    if (message.devicePubkey.length !== 0) {
      obj.devicePubkey = base64FromBytes(message.devicePubkey);
    }
    if (message.deviceRandom.length !== 0) {
      obj.deviceRandom = base64FromBytes(message.deviceRandom);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SessionResp0>, I>>(base?: I): SessionResp0 {
    return SessionResp0.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SessionResp0>, I>>(object: I): SessionResp0 {
    const message = createBaseSessionResp0();
    message.status = object.status ?? 0;
    message.devicePubkey = object.devicePubkey ?? new Uint8Array(0);
    message.deviceRandom = object.deviceRandom ?? new Uint8Array(0);
    return message;
  },
};

function createBaseSec1Payload(): Sec1Payload {
  return { msg: 0, sc0: undefined, sr0: undefined, sc1: undefined, sr1: undefined };
}

export const Sec1Payload: MessageFns<Sec1Payload> = {
  encode(message: Sec1Payload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.msg !== 0) {
      writer.uint32(8).int32(message.msg);
    }
    if (message.sc0 !== undefined) {
      SessionCmd0.encode(message.sc0, writer.uint32(162).fork()).join();
    }
    if (message.sr0 !== undefined) {
      SessionResp0.encode(message.sr0, writer.uint32(170).fork()).join();
    }
    if (message.sc1 !== undefined) {
      SessionCmd1.encode(message.sc1, writer.uint32(178).fork()).join();
    }
    if (message.sr1 !== undefined) {
      SessionResp1.encode(message.sr1, writer.uint32(186).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Sec1Payload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSec1Payload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.msg = reader.int32() as any;
          continue;
        }
        case 20: {
          if (tag !== 162) {
            break;
          }

          message.sc0 = SessionCmd0.decode(reader, reader.uint32());
          continue;
        }
        case 21: {
          if (tag !== 170) {
            break;
          }

          message.sr0 = SessionResp0.decode(reader, reader.uint32());
          continue;
        }
        case 22: {
          if (tag !== 178) {
            break;
          }

          message.sc1 = SessionCmd1.decode(reader, reader.uint32());
          continue;
        }
        case 23: {
          if (tag !== 186) {
            break;
          }

          message.sr1 = SessionResp1.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Sec1Payload {
    return {
      msg: isSet(object.msg) ? sec1MsgTypeFromJSON(object.msg) : 0,
      sc0: isSet(object.sc0) ? SessionCmd0.fromJSON(object.sc0) : undefined,
      sr0: isSet(object.sr0) ? SessionResp0.fromJSON(object.sr0) : undefined,
      sc1: isSet(object.sc1) ? SessionCmd1.fromJSON(object.sc1) : undefined,
      sr1: isSet(object.sr1) ? SessionResp1.fromJSON(object.sr1) : undefined,
    };
  },

  toJSON(message: Sec1Payload): unknown {
    const obj: any = {};
    if (message.msg !== 0) {
      obj.msg = sec1MsgTypeToJSON(message.msg);
    }
    if (message.sc0 !== undefined) {
      obj.sc0 = SessionCmd0.toJSON(message.sc0);
    }
    if (message.sr0 !== undefined) {
      obj.sr0 = SessionResp0.toJSON(message.sr0);
    }
    if (message.sc1 !== undefined) {
      obj.sc1 = SessionCmd1.toJSON(message.sc1);
    }
    if (message.sr1 !== undefined) {
      obj.sr1 = SessionResp1.toJSON(message.sr1);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Sec1Payload>, I>>(base?: I): Sec1Payload {
    return Sec1Payload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Sec1Payload>, I>>(object: I): Sec1Payload {
    const message = createBaseSec1Payload();
    message.msg = object.msg ?? 0;
    message.sc0 = (object.sc0 !== undefined && object.sc0 !== null) ? SessionCmd0.fromPartial(object.sc0) : undefined;
    message.sr0 = (object.sr0 !== undefined && object.sr0 !== null) ? SessionResp0.fromPartial(object.sr0) : undefined;
    message.sc1 = (object.sc1 !== undefined && object.sc1 !== null) ? SessionCmd1.fromPartial(object.sc1) : undefined;
    message.sr1 = (object.sr1 !== undefined && object.sr1 !== null) ? SessionResp1.fromPartial(object.sr1) : undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
