// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: sec2.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Status, statusFromJSON, statusToJSON } from "./constants";

export const protobufPackage = "";

/** A message must be of type Cmd0 / Cmd1 / Resp0 / Resp1 */
export enum Sec2MsgType {
  S2Session_Command0 = 0,
  S2Session_Response0 = 1,
  S2Session_Command1 = 2,
  S2Session_Response1 = 3,
  UNRECOGNIZED = -1,
}

export function sec2MsgTypeFromJSON(object: any): Sec2MsgType {
  switch (object) {
    case 0:
    case "S2Session_Command0":
      return Sec2MsgType.S2Session_Command0;
    case 1:
    case "S2Session_Response0":
      return Sec2MsgType.S2Session_Response0;
    case 2:
    case "S2Session_Command1":
      return Sec2MsgType.S2Session_Command1;
    case 3:
    case "S2Session_Response1":
      return Sec2MsgType.S2Session_Response1;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Sec2MsgType.UNRECOGNIZED;
  }
}

export function sec2MsgTypeToJSON(object: Sec2MsgType): string {
  switch (object) {
    case Sec2MsgType.S2Session_Command0:
      return "S2Session_Command0";
    case Sec2MsgType.S2Session_Response0:
      return "S2Session_Response0";
    case Sec2MsgType.S2Session_Command1:
      return "S2Session_Command1";
    case Sec2MsgType.S2Session_Response1:
      return "S2Session_Response1";
    case Sec2MsgType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Data structure of Session command0 packet */
export interface S2SessionCmd0 {
  clientUsername: Uint8Array;
  clientPubkey: Uint8Array;
}

/** Data structure of Session response0 packet */
export interface S2SessionResp0 {
  status: Status;
  devicePubkey: Uint8Array;
  deviceSalt: Uint8Array;
}

/** Data structure of Session command1 packet */
export interface S2SessionCmd1 {
  clientProof: Uint8Array;
}

/** Data structure of Session response1 packet */
export interface S2SessionResp1 {
  status: Status;
  deviceProof: Uint8Array;
  deviceNonce: Uint8Array;
}

/** Payload structure of session data */
export interface Sec2Payload {
  /** !< Type of message */
  msg: Sec2MsgType;
  /** !< Payload data interpreted as Cmd0 */
  sc0?:
    | S2SessionCmd0
    | undefined;
  /** !< Payload data interpreted as Resp0 */
  sr0?:
    | S2SessionResp0
    | undefined;
  /** !< Payload data interpreted as Cmd1 */
  sc1?:
    | S2SessionCmd1
    | undefined;
  /** !< Payload data interpreted as Resp1 */
  sr1?: S2SessionResp1 | undefined;
}

function createBaseS2SessionCmd0(): S2SessionCmd0 {
  return { clientUsername: new Uint8Array(0), clientPubkey: new Uint8Array(0) };
}

export const S2SessionCmd0: MessageFns<S2SessionCmd0> = {
  encode(message: S2SessionCmd0, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clientUsername.length !== 0) {
      writer.uint32(10).bytes(message.clientUsername);
    }
    if (message.clientPubkey.length !== 0) {
      writer.uint32(18).bytes(message.clientPubkey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): S2SessionCmd0 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseS2SessionCmd0();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clientUsername = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clientPubkey = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): S2SessionCmd0 {
    return {
      clientUsername: isSet(object.clientUsername)
        ? bytesFromBase64(object.clientUsername)
        : isSet(object.client_username)
        ? bytesFromBase64(object.client_username)
        : new Uint8Array(0),
      clientPubkey: isSet(object.clientPubkey)
        ? bytesFromBase64(object.clientPubkey)
        : isSet(object.client_pubkey)
        ? bytesFromBase64(object.client_pubkey)
        : new Uint8Array(0),
    };
  },

  toJSON(message: S2SessionCmd0): unknown {
    const obj: any = {};
    if (message.clientUsername.length !== 0) {
      obj.clientUsername = base64FromBytes(message.clientUsername);
    }
    if (message.clientPubkey.length !== 0) {
      obj.clientPubkey = base64FromBytes(message.clientPubkey);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<S2SessionCmd0>, I>>(base?: I): S2SessionCmd0 {
    return S2SessionCmd0.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<S2SessionCmd0>, I>>(object: I): S2SessionCmd0 {
    const message = createBaseS2SessionCmd0();
    message.clientUsername = object.clientUsername ?? new Uint8Array(0);
    message.clientPubkey = object.clientPubkey ?? new Uint8Array(0);
    return message;
  },
};

function createBaseS2SessionResp0(): S2SessionResp0 {
  return { status: 0, devicePubkey: new Uint8Array(0), deviceSalt: new Uint8Array(0) };
}

export const S2SessionResp0: MessageFns<S2SessionResp0> = {
  encode(message: S2SessionResp0, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== 0) {
      writer.uint32(8).int32(message.status);
    }
    if (message.devicePubkey.length !== 0) {
      writer.uint32(18).bytes(message.devicePubkey);
    }
    if (message.deviceSalt.length !== 0) {
      writer.uint32(26).bytes(message.deviceSalt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): S2SessionResp0 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseS2SessionResp0();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.devicePubkey = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.deviceSalt = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): S2SessionResp0 {
    return {
      status: isSet(object.status) ? statusFromJSON(object.status) : 0,
      devicePubkey: isSet(object.devicePubkey)
        ? bytesFromBase64(object.devicePubkey)
        : isSet(object.device_pubkey)
        ? bytesFromBase64(object.device_pubkey)
        : new Uint8Array(0),
      deviceSalt: isSet(object.deviceSalt)
        ? bytesFromBase64(object.deviceSalt)
        : isSet(object.device_salt)
        ? bytesFromBase64(object.device_salt)
        : new Uint8Array(0),
    };
  },

  toJSON(message: S2SessionResp0): unknown {
    const obj: any = {};
    if (message.status !== 0) {
      obj.status = statusToJSON(message.status);
    }
    if (message.devicePubkey.length !== 0) {
      obj.devicePubkey = base64FromBytes(message.devicePubkey);
    }
    if (message.deviceSalt.length !== 0) {
      obj.deviceSalt = base64FromBytes(message.deviceSalt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<S2SessionResp0>, I>>(base?: I): S2SessionResp0 {
    return S2SessionResp0.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<S2SessionResp0>, I>>(object: I): S2SessionResp0 {
    const message = createBaseS2SessionResp0();
    message.status = object.status ?? 0;
    message.devicePubkey = object.devicePubkey ?? new Uint8Array(0);
    message.deviceSalt = object.deviceSalt ?? new Uint8Array(0);
    return message;
  },
};

function createBaseS2SessionCmd1(): S2SessionCmd1 {
  return { clientProof: new Uint8Array(0) };
}

export const S2SessionCmd1: MessageFns<S2SessionCmd1> = {
  encode(message: S2SessionCmd1, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clientProof.length !== 0) {
      writer.uint32(10).bytes(message.clientProof);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): S2SessionCmd1 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseS2SessionCmd1();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clientProof = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): S2SessionCmd1 {
    return {
      clientProof: isSet(object.clientProof)
        ? bytesFromBase64(object.clientProof)
        : isSet(object.client_proof)
        ? bytesFromBase64(object.client_proof)
        : new Uint8Array(0),
    };
  },

  toJSON(message: S2SessionCmd1): unknown {
    const obj: any = {};
    if (message.clientProof.length !== 0) {
      obj.clientProof = base64FromBytes(message.clientProof);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<S2SessionCmd1>, I>>(base?: I): S2SessionCmd1 {
    return S2SessionCmd1.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<S2SessionCmd1>, I>>(object: I): S2SessionCmd1 {
    const message = createBaseS2SessionCmd1();
    message.clientProof = object.clientProof ?? new Uint8Array(0);
    return message;
  },
};

function createBaseS2SessionResp1(): S2SessionResp1 {
  return { status: 0, deviceProof: new Uint8Array(0), deviceNonce: new Uint8Array(0) };
}

export const S2SessionResp1: MessageFns<S2SessionResp1> = {
  encode(message: S2SessionResp1, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== 0) {
      writer.uint32(8).int32(message.status);
    }
    if (message.deviceProof.length !== 0) {
      writer.uint32(18).bytes(message.deviceProof);
    }
    if (message.deviceNonce.length !== 0) {
      writer.uint32(26).bytes(message.deviceNonce);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): S2SessionResp1 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseS2SessionResp1();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.deviceProof = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.deviceNonce = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): S2SessionResp1 {
    return {
      status: isSet(object.status) ? statusFromJSON(object.status) : 0,
      deviceProof: isSet(object.deviceProof)
        ? bytesFromBase64(object.deviceProof)
        : isSet(object.device_proof)
        ? bytesFromBase64(object.device_proof)
        : new Uint8Array(0),
      deviceNonce: isSet(object.deviceNonce)
        ? bytesFromBase64(object.deviceNonce)
        : isSet(object.device_nonce)
        ? bytesFromBase64(object.device_nonce)
        : new Uint8Array(0),
    };
  },

  toJSON(message: S2SessionResp1): unknown {
    const obj: any = {};
    if (message.status !== 0) {
      obj.status = statusToJSON(message.status);
    }
    if (message.deviceProof.length !== 0) {
      obj.deviceProof = base64FromBytes(message.deviceProof);
    }
    if (message.deviceNonce.length !== 0) {
      obj.deviceNonce = base64FromBytes(message.deviceNonce);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<S2SessionResp1>, I>>(base?: I): S2SessionResp1 {
    return S2SessionResp1.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<S2SessionResp1>, I>>(object: I): S2SessionResp1 {
    const message = createBaseS2SessionResp1();
    message.status = object.status ?? 0;
    message.deviceProof = object.deviceProof ?? new Uint8Array(0);
    message.deviceNonce = object.deviceNonce ?? new Uint8Array(0);
    return message;
  },
};

function createBaseSec2Payload(): Sec2Payload {
  return { msg: 0, sc0: undefined, sr0: undefined, sc1: undefined, sr1: undefined };
}

export const Sec2Payload: MessageFns<Sec2Payload> = {
  encode(message: Sec2Payload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.msg !== 0) {
      writer.uint32(8).int32(message.msg);
    }
    if (message.sc0 !== undefined) {
      S2SessionCmd0.encode(message.sc0, writer.uint32(162).fork()).join();
    }
    if (message.sr0 !== undefined) {
      S2SessionResp0.encode(message.sr0, writer.uint32(170).fork()).join();
    }
    if (message.sc1 !== undefined) {
      S2SessionCmd1.encode(message.sc1, writer.uint32(178).fork()).join();
    }
    if (message.sr1 !== undefined) {
      S2SessionResp1.encode(message.sr1, writer.uint32(186).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Sec2Payload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSec2Payload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.msg = reader.int32() as any;
          continue;
        }
        case 20: {
          if (tag !== 162) {
            break;
          }

          message.sc0 = S2SessionCmd0.decode(reader, reader.uint32());
          continue;
        }
        case 21: {
          if (tag !== 170) {
            break;
          }

          message.sr0 = S2SessionResp0.decode(reader, reader.uint32());
          continue;
        }
        case 22: {
          if (tag !== 178) {
            break;
          }

          message.sc1 = S2SessionCmd1.decode(reader, reader.uint32());
          continue;
        }
        case 23: {
          if (tag !== 186) {
            break;
          }

          message.sr1 = S2SessionResp1.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Sec2Payload {
    return {
      msg: isSet(object.msg) ? sec2MsgTypeFromJSON(object.msg) : 0,
      sc0: isSet(object.sc0) ? S2SessionCmd0.fromJSON(object.sc0) : undefined,
      sr0: isSet(object.sr0) ? S2SessionResp0.fromJSON(object.sr0) : undefined,
      sc1: isSet(object.sc1) ? S2SessionCmd1.fromJSON(object.sc1) : undefined,
      sr1: isSet(object.sr1) ? S2SessionResp1.fromJSON(object.sr1) : undefined,
    };
  },

  toJSON(message: Sec2Payload): unknown {
    const obj: any = {};
    if (message.msg !== 0) {
      obj.msg = sec2MsgTypeToJSON(message.msg);
    }
    if (message.sc0 !== undefined) {
      obj.sc0 = S2SessionCmd0.toJSON(message.sc0);
    }
    if (message.sr0 !== undefined) {
      obj.sr0 = S2SessionResp0.toJSON(message.sr0);
    }
    if (message.sc1 !== undefined) {
      obj.sc1 = S2SessionCmd1.toJSON(message.sc1);
    }
    if (message.sr1 !== undefined) {
      obj.sr1 = S2SessionResp1.toJSON(message.sr1);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Sec2Payload>, I>>(base?: I): Sec2Payload {
    return Sec2Payload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Sec2Payload>, I>>(object: I): Sec2Payload {
    const message = createBaseSec2Payload();
    message.msg = object.msg ?? 0;
    message.sc0 = (object.sc0 !== undefined && object.sc0 !== null) ? S2SessionCmd0.fromPartial(object.sc0) : undefined;
    message.sr0 = (object.sr0 !== undefined && object.sr0 !== null)
      ? S2SessionResp0.fromPartial(object.sr0)
      : undefined;
    message.sc1 = (object.sc1 !== undefined && object.sc1 !== null) ? S2SessionCmd1.fromPartial(object.sc1) : undefined;
    message.sr1 = (object.sr1 !== undefined && object.sr1 !== null)
      ? S2SessionResp1.fromPartial(object.sr1)
      : undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
