// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: session.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Sec0Payload } from "./sec0";
import { Sec1Payload } from "./sec1";
import { Sec2Payload } from "./sec2";

export const protobufPackage = "";

/**
 * Allowed values for the type of security
 * being used in a protocomm session
 */
export enum SecSchemeVersion {
  /** SecScheme0 - !< Unsecured - plaintext communication */
  SecScheme0 = 0,
  /** SecScheme1 - !< Security scheme 1 - Curve25519 + AES-256-CTR */
  SecScheme1 = 1,
  /** SecScheme2 - !< Security scheme 2 - SRP6a + AES-256-GCM */
  SecScheme2 = 2,
  UNRECOGNIZED = -1,
}

export function secSchemeVersionFromJSON(object: any): SecSchemeVersion {
  switch (object) {
    case 0:
    case "SecScheme0":
      return SecSchemeVersion.SecScheme0;
    case 1:
    case "SecScheme1":
      return SecSchemeVersion.SecScheme1;
    case 2:
    case "SecScheme2":
      return SecSchemeVersion.SecScheme2;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SecSchemeVersion.UNRECOGNIZED;
  }
}

export function secSchemeVersionToJSON(object: SecSchemeVersion): string {
  switch (object) {
    case SecSchemeVersion.SecScheme0:
      return "SecScheme0";
    case SecSchemeVersion.SecScheme1:
      return "SecScheme1";
    case SecSchemeVersion.SecScheme2:
      return "SecScheme2";
    case SecSchemeVersion.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * Data structure exchanged when establishing
 * secure session between Host and Client
 */
export interface SessionData {
  /** !< Type of security */
  secVer: SecSchemeVersion;
  /** !< Payload data in case of security 0 */
  sec0?:
    | Sec0Payload
    | undefined;
  /** !< Payload data in case of security 1 */
  sec1?:
    | Sec1Payload
    | undefined;
  /** !< Payload data in case of security 2 */
  sec2?: Sec2Payload | undefined;
}

function createBaseSessionData(): SessionData {
  return { secVer: 0, sec0: undefined, sec1: undefined, sec2: undefined };
}

export const SessionData: MessageFns<SessionData> = {
  encode(message: SessionData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.secVer !== 0) {
      writer.uint32(16).int32(message.secVer);
    }
    if (message.sec0 !== undefined) {
      Sec0Payload.encode(message.sec0, writer.uint32(82).fork()).join();
    }
    if (message.sec1 !== undefined) {
      Sec1Payload.encode(message.sec1, writer.uint32(90).fork()).join();
    }
    if (message.sec2 !== undefined) {
      Sec2Payload.encode(message.sec2, writer.uint32(98).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.secVer = reader.int32() as any;
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.sec0 = Sec0Payload.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.sec1 = Sec1Payload.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.sec2 = Sec2Payload.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SessionData {
    return {
      secVer: isSet(object.secVer)
        ? secSchemeVersionFromJSON(object.secVer)
        : isSet(object.sec_ver)
        ? secSchemeVersionFromJSON(object.sec_ver)
        : 0,
      sec0: isSet(object.sec0) ? Sec0Payload.fromJSON(object.sec0) : undefined,
      sec1: isSet(object.sec1) ? Sec1Payload.fromJSON(object.sec1) : undefined,
      sec2: isSet(object.sec2) ? Sec2Payload.fromJSON(object.sec2) : undefined,
    };
  },

  toJSON(message: SessionData): unknown {
    const obj: any = {};
    if (message.secVer !== 0) {
      obj.secVer = secSchemeVersionToJSON(message.secVer);
    }
    if (message.sec0 !== undefined) {
      obj.sec0 = Sec0Payload.toJSON(message.sec0);
    }
    if (message.sec1 !== undefined) {
      obj.sec1 = Sec1Payload.toJSON(message.sec1);
    }
    if (message.sec2 !== undefined) {
      obj.sec2 = Sec2Payload.toJSON(message.sec2);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SessionData>, I>>(base?: I): SessionData {
    return SessionData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SessionData>, I>>(object: I): SessionData {
    const message = createBaseSessionData();
    message.secVer = object.secVer ?? 0;
    message.sec0 = (object.sec0 !== undefined && object.sec0 !== null)
      ? Sec0Payload.fromPartial(object.sec0)
      : undefined;
    message.sec1 = (object.sec1 !== undefined && object.sec1 !== null)
      ? Sec1Payload.fromPartial(object.sec1)
      : undefined;
    message.sec2 = (object.sec2 !== undefined && object.sec2 !== null)
      ? Sec2Payload.fromPartial(object.sec2)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
