// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: wifi_constants.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export enum WifiStationState {
  Connected = 0,
  Connecting = 1,
  Disconnected = 2,
  ConnectionFailed = 3,
  UNRECOGNIZED = -1,
}

export function wifiStationStateFromJSON(object: any): WifiStationState {
  switch (object) {
    case 0:
    case "Connected":
      return WifiStationState.Connected;
    case 1:
    case "Connecting":
      return WifiStationState.Connecting;
    case 2:
    case "Disconnected":
      return WifiStationState.Disconnected;
    case 3:
    case "ConnectionFailed":
      return WifiStationState.ConnectionFailed;
    case -1:
    case "UNRECOGNIZED":
    default:
      return WifiStationState.UNRECOGNIZED;
  }
}

export function wifiStationStateToJSON(object: WifiStationState): string {
  switch (object) {
    case WifiStationState.Connected:
      return "Connected";
    case WifiStationState.Connecting:
      return "Connecting";
    case WifiStationState.Disconnected:
      return "Disconnected";
    case WifiStationState.ConnectionFailed:
      return "ConnectionFailed";
    case WifiStationState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum WifiConnectFailedReason {
  AuthError = 0,
  NetworkNotFound = 1,
  UNRECOGNIZED = -1,
}

export function wifiConnectFailedReasonFromJSON(object: any): WifiConnectFailedReason {
  switch (object) {
    case 0:
    case "AuthError":
      return WifiConnectFailedReason.AuthError;
    case 1:
    case "NetworkNotFound":
      return WifiConnectFailedReason.NetworkNotFound;
    case -1:
    case "UNRECOGNIZED":
    default:
      return WifiConnectFailedReason.UNRECOGNIZED;
  }
}

export function wifiConnectFailedReasonToJSON(object: WifiConnectFailedReason): string {
  switch (object) {
    case WifiConnectFailedReason.AuthError:
      return "AuthError";
    case WifiConnectFailedReason.NetworkNotFound:
      return "NetworkNotFound";
    case WifiConnectFailedReason.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum WifiAuthMode {
  Open = 0,
  WEP = 1,
  WPA_PSK = 2,
  WPA2_PSK = 3,
  WPA_WPA2_PSK = 4,
  WPA2_ENTERPRISE = 5,
  WPA3_PSK = 6,
  WPA2_WPA3_PSK = 7,
  UNRECOGNIZED = -1,
}

export function wifiAuthModeFromJSON(object: any): WifiAuthMode {
  switch (object) {
    case 0:
    case "Open":
      return WifiAuthMode.Open;
    case 1:
    case "WEP":
      return WifiAuthMode.WEP;
    case 2:
    case "WPA_PSK":
      return WifiAuthMode.WPA_PSK;
    case 3:
    case "WPA2_PSK":
      return WifiAuthMode.WPA2_PSK;
    case 4:
    case "WPA_WPA2_PSK":
      return WifiAuthMode.WPA_WPA2_PSK;
    case 5:
    case "WPA2_ENTERPRISE":
      return WifiAuthMode.WPA2_ENTERPRISE;
    case 6:
    case "WPA3_PSK":
      return WifiAuthMode.WPA3_PSK;
    case 7:
    case "WPA2_WPA3_PSK":
      return WifiAuthMode.WPA2_WPA3_PSK;
    case -1:
    case "UNRECOGNIZED":
    default:
      return WifiAuthMode.UNRECOGNIZED;
  }
}

export function wifiAuthModeToJSON(object: WifiAuthMode): string {
  switch (object) {
    case WifiAuthMode.Open:
      return "Open";
    case WifiAuthMode.WEP:
      return "WEP";
    case WifiAuthMode.WPA_PSK:
      return "WPA_PSK";
    case WifiAuthMode.WPA2_PSK:
      return "WPA2_PSK";
    case WifiAuthMode.WPA_WPA2_PSK:
      return "WPA_WPA2_PSK";
    case WifiAuthMode.WPA2_ENTERPRISE:
      return "WPA2_ENTERPRISE";
    case WifiAuthMode.WPA3_PSK:
      return "WPA3_PSK";
    case WifiAuthMode.WPA2_WPA3_PSK:
      return "WPA2_WPA3_PSK";
    case WifiAuthMode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface WifiAttemptFailed {
  attemptsRemaining: number;
}

export interface WifiConnectedState {
  ip4Addr: string;
  authMode: WifiAuthMode;
  ssid: Uint8Array;
  bssid: Uint8Array;
  channel: number;
}

function createBaseWifiAttemptFailed(): WifiAttemptFailed {
  return { attemptsRemaining: 0 };
}

export const WifiAttemptFailed: MessageFns<WifiAttemptFailed> = {
  encode(message: WifiAttemptFailed, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.attemptsRemaining !== 0) {
      writer.uint32(8).uint32(message.attemptsRemaining);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WifiAttemptFailed {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWifiAttemptFailed();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.attemptsRemaining = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WifiAttemptFailed {
    return {
      attemptsRemaining: isSet(object.attemptsRemaining)
        ? globalThis.Number(object.attemptsRemaining)
        : isSet(object.attempts_remaining)
        ? globalThis.Number(object.attempts_remaining)
        : 0,
    };
  },

  toJSON(message: WifiAttemptFailed): unknown {
    const obj: any = {};
    if (message.attemptsRemaining !== 0) {
      obj.attemptsRemaining = Math.round(message.attemptsRemaining);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WifiAttemptFailed>, I>>(base?: I): WifiAttemptFailed {
    return WifiAttemptFailed.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WifiAttemptFailed>, I>>(object: I): WifiAttemptFailed {
    const message = createBaseWifiAttemptFailed();
    message.attemptsRemaining = object.attemptsRemaining ?? 0;
    return message;
  },
};

function createBaseWifiConnectedState(): WifiConnectedState {
  return { ip4Addr: "", authMode: 0, ssid: new Uint8Array(0), bssid: new Uint8Array(0), channel: 0 };
}

export const WifiConnectedState: MessageFns<WifiConnectedState> = {
  encode(message: WifiConnectedState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ip4Addr !== "") {
      writer.uint32(10).string(message.ip4Addr);
    }
    if (message.authMode !== 0) {
      writer.uint32(16).int32(message.authMode);
    }
    if (message.ssid.length !== 0) {
      writer.uint32(26).bytes(message.ssid);
    }
    if (message.bssid.length !== 0) {
      writer.uint32(34).bytes(message.bssid);
    }
    if (message.channel !== 0) {
      writer.uint32(40).int32(message.channel);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WifiConnectedState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWifiConnectedState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ip4Addr = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.authMode = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.ssid = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.bssid = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.channel = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WifiConnectedState {
    return {
      ip4Addr: isSet(object.ip4Addr)
        ? globalThis.String(object.ip4Addr)
        : isSet(object.ip4_addr)
        ? globalThis.String(object.ip4_addr)
        : "",
      authMode: isSet(object.authMode)
        ? wifiAuthModeFromJSON(object.authMode)
        : isSet(object.auth_mode)
        ? wifiAuthModeFromJSON(object.auth_mode)
        : 0,
      ssid: isSet(object.ssid) ? bytesFromBase64(object.ssid) : new Uint8Array(0),
      bssid: isSet(object.bssid) ? bytesFromBase64(object.bssid) : new Uint8Array(0),
      channel: isSet(object.channel) ? globalThis.Number(object.channel) : 0,
    };
  },

  toJSON(message: WifiConnectedState): unknown {
    const obj: any = {};
    if (message.ip4Addr !== "") {
      obj.ip4Addr = message.ip4Addr;
    }
    if (message.authMode !== 0) {
      obj.authMode = wifiAuthModeToJSON(message.authMode);
    }
    if (message.ssid.length !== 0) {
      obj.ssid = base64FromBytes(message.ssid);
    }
    if (message.bssid.length !== 0) {
      obj.bssid = base64FromBytes(message.bssid);
    }
    if (message.channel !== 0) {
      obj.channel = Math.round(message.channel);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WifiConnectedState>, I>>(base?: I): WifiConnectedState {
    return WifiConnectedState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WifiConnectedState>, I>>(object: I): WifiConnectedState {
    const message = createBaseWifiConnectedState();
    message.ip4Addr = object.ip4Addr ?? "";
    message.authMode = object.authMode ?? 0;
    message.ssid = object.ssid ?? new Uint8Array(0);
    message.bssid = object.bssid ?? new Uint8Array(0);
    message.channel = object.channel ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
