// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: wifi_config.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Status, statusFromJSON, statusToJSON } from "./constants";
import {
  WifiAttemptFailed,
  WifiConnectedState,
  WifiConnectFailedReason,
  wifiConnectFailedReasonFromJSON,
  wifiConnectFailedReasonToJSON,
  WifiStationState,
  wifiStationStateFromJSON,
  wifiStationStateToJSON,
} from "./wifi_constants";

export const protobufPackage = "";

export enum WiFiConfigMsgType {
  TypeCmdGetStatus = 0,
  TypeRespGetStatus = 1,
  TypeCmdSetConfig = 2,
  TypeRespSetConfig = 3,
  TypeCmdApplyConfig = 4,
  TypeRespApplyConfig = 5,
  UNRECOGNIZED = -1,
}

export function wiFiConfigMsgTypeFromJSON(object: any): WiFiConfigMsgType {
  switch (object) {
    case 0:
    case "TypeCmdGetStatus":
      return WiFiConfigMsgType.TypeCmdGetStatus;
    case 1:
    case "TypeRespGetStatus":
      return WiFiConfigMsgType.TypeRespGetStatus;
    case 2:
    case "TypeCmdSetConfig":
      return WiFiConfigMsgType.TypeCmdSetConfig;
    case 3:
    case "TypeRespSetConfig":
      return WiFiConfigMsgType.TypeRespSetConfig;
    case 4:
    case "TypeCmdApplyConfig":
      return WiFiConfigMsgType.TypeCmdApplyConfig;
    case 5:
    case "TypeRespApplyConfig":
      return WiFiConfigMsgType.TypeRespApplyConfig;
    case -1:
    case "UNRECOGNIZED":
    default:
      return WiFiConfigMsgType.UNRECOGNIZED;
  }
}

export function wiFiConfigMsgTypeToJSON(object: WiFiConfigMsgType): string {
  switch (object) {
    case WiFiConfigMsgType.TypeCmdGetStatus:
      return "TypeCmdGetStatus";
    case WiFiConfigMsgType.TypeRespGetStatus:
      return "TypeRespGetStatus";
    case WiFiConfigMsgType.TypeCmdSetConfig:
      return "TypeCmdSetConfig";
    case WiFiConfigMsgType.TypeRespSetConfig:
      return "TypeRespSetConfig";
    case WiFiConfigMsgType.TypeCmdApplyConfig:
      return "TypeCmdApplyConfig";
    case WiFiConfigMsgType.TypeRespApplyConfig:
      return "TypeRespApplyConfig";
    case WiFiConfigMsgType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface CmdGetStatus {
}

export interface RespGetStatus {
  status: Status;
  staState: WifiStationState;
  failReason?: WifiConnectFailedReason | undefined;
  connected?: WifiConnectedState | undefined;
  attemptFailed?: WifiAttemptFailed | undefined;
}

export interface CmdSetConfig {
  ssid: Uint8Array;
  passphrase: Uint8Array;
  bssid: Uint8Array;
  channel: number;
}

export interface RespSetConfig {
  status: Status;
}

export interface CmdApplyConfig {
}

export interface RespApplyConfig {
  status: Status;
}

export interface WiFiConfigPayload {
  msg: WiFiConfigMsgType;
  cmdGetStatus?: CmdGetStatus | undefined;
  respGetStatus?: RespGetStatus | undefined;
  cmdSetConfig?: CmdSetConfig | undefined;
  respSetConfig?: RespSetConfig | undefined;
  cmdApplyConfig?: CmdApplyConfig | undefined;
  respApplyConfig?: RespApplyConfig | undefined;
}

function createBaseCmdGetStatus(): CmdGetStatus {
  return {};
}

export const CmdGetStatus: MessageFns<CmdGetStatus> = {
  encode(_: CmdGetStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CmdGetStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCmdGetStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CmdGetStatus {
    return {};
  },

  toJSON(_: CmdGetStatus): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CmdGetStatus>, I>>(base?: I): CmdGetStatus {
    return CmdGetStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CmdGetStatus>, I>>(_: I): CmdGetStatus {
    const message = createBaseCmdGetStatus();
    return message;
  },
};

function createBaseRespGetStatus(): RespGetStatus {
  return { status: 0, staState: 0, failReason: undefined, connected: undefined, attemptFailed: undefined };
}

export const RespGetStatus: MessageFns<RespGetStatus> = {
  encode(message: RespGetStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== 0) {
      writer.uint32(8).int32(message.status);
    }
    if (message.staState !== 0) {
      writer.uint32(16).int32(message.staState);
    }
    if (message.failReason !== undefined) {
      writer.uint32(80).int32(message.failReason);
    }
    if (message.connected !== undefined) {
      WifiConnectedState.encode(message.connected, writer.uint32(90).fork()).join();
    }
    if (message.attemptFailed !== undefined) {
      WifiAttemptFailed.encode(message.attemptFailed, writer.uint32(98).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RespGetStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRespGetStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.staState = reader.int32() as any;
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.failReason = reader.int32() as any;
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.connected = WifiConnectedState.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.attemptFailed = WifiAttemptFailed.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RespGetStatus {
    return {
      status: isSet(object.status) ? statusFromJSON(object.status) : 0,
      staState: isSet(object.staState)
        ? wifiStationStateFromJSON(object.staState)
        : isSet(object.sta_state)
        ? wifiStationStateFromJSON(object.sta_state)
        : 0,
      failReason: isSet(object.failReason)
        ? wifiConnectFailedReasonFromJSON(object.failReason)
        : isSet(object.fail_reason)
        ? wifiConnectFailedReasonFromJSON(object.fail_reason)
        : undefined,
      connected: isSet(object.connected) ? WifiConnectedState.fromJSON(object.connected) : undefined,
      attemptFailed: isSet(object.attemptFailed)
        ? WifiAttemptFailed.fromJSON(object.attemptFailed)
        : isSet(object.attempt_failed)
        ? WifiAttemptFailed.fromJSON(object.attempt_failed)
        : undefined,
    };
  },

  toJSON(message: RespGetStatus): unknown {
    const obj: any = {};
    if (message.status !== 0) {
      obj.status = statusToJSON(message.status);
    }
    if (message.staState !== 0) {
      obj.staState = wifiStationStateToJSON(message.staState);
    }
    if (message.failReason !== undefined) {
      obj.failReason = wifiConnectFailedReasonToJSON(message.failReason);
    }
    if (message.connected !== undefined) {
      obj.connected = WifiConnectedState.toJSON(message.connected);
    }
    if (message.attemptFailed !== undefined) {
      obj.attemptFailed = WifiAttemptFailed.toJSON(message.attemptFailed);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RespGetStatus>, I>>(base?: I): RespGetStatus {
    return RespGetStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RespGetStatus>, I>>(object: I): RespGetStatus {
    const message = createBaseRespGetStatus();
    message.status = object.status ?? 0;
    message.staState = object.staState ?? 0;
    message.failReason = object.failReason ?? undefined;
    message.connected = (object.connected !== undefined && object.connected !== null)
      ? WifiConnectedState.fromPartial(object.connected)
      : undefined;
    message.attemptFailed = (object.attemptFailed !== undefined && object.attemptFailed !== null)
      ? WifiAttemptFailed.fromPartial(object.attemptFailed)
      : undefined;
    return message;
  },
};

function createBaseCmdSetConfig(): CmdSetConfig {
  return { ssid: new Uint8Array(0), passphrase: new Uint8Array(0), bssid: new Uint8Array(0), channel: 0 };
}

export const CmdSetConfig: MessageFns<CmdSetConfig> = {
  encode(message: CmdSetConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ssid.length !== 0) {
      writer.uint32(10).bytes(message.ssid);
    }
    if (message.passphrase.length !== 0) {
      writer.uint32(18).bytes(message.passphrase);
    }
    if (message.bssid.length !== 0) {
      writer.uint32(26).bytes(message.bssid);
    }
    if (message.channel !== 0) {
      writer.uint32(32).int32(message.channel);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CmdSetConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCmdSetConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ssid = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.passphrase = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.bssid = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.channel = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CmdSetConfig {
    return {
      ssid: isSet(object.ssid) ? bytesFromBase64(object.ssid) : new Uint8Array(0),
      passphrase: isSet(object.passphrase) ? bytesFromBase64(object.passphrase) : new Uint8Array(0),
      bssid: isSet(object.bssid) ? bytesFromBase64(object.bssid) : new Uint8Array(0),
      channel: isSet(object.channel) ? globalThis.Number(object.channel) : 0,
    };
  },

  toJSON(message: CmdSetConfig): unknown {
    const obj: any = {};
    if (message.ssid.length !== 0) {
      obj.ssid = base64FromBytes(message.ssid);
    }
    if (message.passphrase.length !== 0) {
      obj.passphrase = base64FromBytes(message.passphrase);
    }
    if (message.bssid.length !== 0) {
      obj.bssid = base64FromBytes(message.bssid);
    }
    if (message.channel !== 0) {
      obj.channel = Math.round(message.channel);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CmdSetConfig>, I>>(base?: I): CmdSetConfig {
    return CmdSetConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CmdSetConfig>, I>>(object: I): CmdSetConfig {
    const message = createBaseCmdSetConfig();
    message.ssid = object.ssid ?? new Uint8Array(0);
    message.passphrase = object.passphrase ?? new Uint8Array(0);
    message.bssid = object.bssid ?? new Uint8Array(0);
    message.channel = object.channel ?? 0;
    return message;
  },
};

function createBaseRespSetConfig(): RespSetConfig {
  return { status: 0 };
}

export const RespSetConfig: MessageFns<RespSetConfig> = {
  encode(message: RespSetConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== 0) {
      writer.uint32(8).int32(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RespSetConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRespSetConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RespSetConfig {
    return { status: isSet(object.status) ? statusFromJSON(object.status) : 0 };
  },

  toJSON(message: RespSetConfig): unknown {
    const obj: any = {};
    if (message.status !== 0) {
      obj.status = statusToJSON(message.status);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RespSetConfig>, I>>(base?: I): RespSetConfig {
    return RespSetConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RespSetConfig>, I>>(object: I): RespSetConfig {
    const message = createBaseRespSetConfig();
    message.status = object.status ?? 0;
    return message;
  },
};

function createBaseCmdApplyConfig(): CmdApplyConfig {
  return {};
}

export const CmdApplyConfig: MessageFns<CmdApplyConfig> = {
  encode(_: CmdApplyConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CmdApplyConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCmdApplyConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CmdApplyConfig {
    return {};
  },

  toJSON(_: CmdApplyConfig): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CmdApplyConfig>, I>>(base?: I): CmdApplyConfig {
    return CmdApplyConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CmdApplyConfig>, I>>(_: I): CmdApplyConfig {
    const message = createBaseCmdApplyConfig();
    return message;
  },
};

function createBaseRespApplyConfig(): RespApplyConfig {
  return { status: 0 };
}

export const RespApplyConfig: MessageFns<RespApplyConfig> = {
  encode(message: RespApplyConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== 0) {
      writer.uint32(8).int32(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RespApplyConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRespApplyConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RespApplyConfig {
    return { status: isSet(object.status) ? statusFromJSON(object.status) : 0 };
  },

  toJSON(message: RespApplyConfig): unknown {
    const obj: any = {};
    if (message.status !== 0) {
      obj.status = statusToJSON(message.status);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RespApplyConfig>, I>>(base?: I): RespApplyConfig {
    return RespApplyConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RespApplyConfig>, I>>(object: I): RespApplyConfig {
    const message = createBaseRespApplyConfig();
    message.status = object.status ?? 0;
    return message;
  },
};

function createBaseWiFiConfigPayload(): WiFiConfigPayload {
  return {
    msg: 0,
    cmdGetStatus: undefined,
    respGetStatus: undefined,
    cmdSetConfig: undefined,
    respSetConfig: undefined,
    cmdApplyConfig: undefined,
    respApplyConfig: undefined,
  };
}

export const WiFiConfigPayload: MessageFns<WiFiConfigPayload> = {
  encode(message: WiFiConfigPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.msg !== 0) {
      writer.uint32(8).int32(message.msg);
    }
    if (message.cmdGetStatus !== undefined) {
      CmdGetStatus.encode(message.cmdGetStatus, writer.uint32(82).fork()).join();
    }
    if (message.respGetStatus !== undefined) {
      RespGetStatus.encode(message.respGetStatus, writer.uint32(90).fork()).join();
    }
    if (message.cmdSetConfig !== undefined) {
      CmdSetConfig.encode(message.cmdSetConfig, writer.uint32(98).fork()).join();
    }
    if (message.respSetConfig !== undefined) {
      RespSetConfig.encode(message.respSetConfig, writer.uint32(106).fork()).join();
    }
    if (message.cmdApplyConfig !== undefined) {
      CmdApplyConfig.encode(message.cmdApplyConfig, writer.uint32(114).fork()).join();
    }
    if (message.respApplyConfig !== undefined) {
      RespApplyConfig.encode(message.respApplyConfig, writer.uint32(122).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WiFiConfigPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWiFiConfigPayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.msg = reader.int32() as any;
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.cmdGetStatus = CmdGetStatus.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.respGetStatus = RespGetStatus.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.cmdSetConfig = CmdSetConfig.decode(reader, reader.uint32());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.respSetConfig = RespSetConfig.decode(reader, reader.uint32());
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.cmdApplyConfig = CmdApplyConfig.decode(reader, reader.uint32());
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.respApplyConfig = RespApplyConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WiFiConfigPayload {
    return {
      msg: isSet(object.msg) ? wiFiConfigMsgTypeFromJSON(object.msg) : 0,
      cmdGetStatus: isSet(object.cmdGetStatus)
        ? CmdGetStatus.fromJSON(object.cmdGetStatus)
        : isSet(object.cmd_get_status)
        ? CmdGetStatus.fromJSON(object.cmd_get_status)
        : undefined,
      respGetStatus: isSet(object.respGetStatus)
        ? RespGetStatus.fromJSON(object.respGetStatus)
        : isSet(object.resp_get_status)
        ? RespGetStatus.fromJSON(object.resp_get_status)
        : undefined,
      cmdSetConfig: isSet(object.cmdSetConfig)
        ? CmdSetConfig.fromJSON(object.cmdSetConfig)
        : isSet(object.cmd_set_config)
        ? CmdSetConfig.fromJSON(object.cmd_set_config)
        : undefined,
      respSetConfig: isSet(object.respSetConfig)
        ? RespSetConfig.fromJSON(object.respSetConfig)
        : isSet(object.resp_set_config)
        ? RespSetConfig.fromJSON(object.resp_set_config)
        : undefined,
      cmdApplyConfig: isSet(object.cmdApplyConfig)
        ? CmdApplyConfig.fromJSON(object.cmdApplyConfig)
        : isSet(object.cmd_apply_config)
        ? CmdApplyConfig.fromJSON(object.cmd_apply_config)
        : undefined,
      respApplyConfig: isSet(object.respApplyConfig)
        ? RespApplyConfig.fromJSON(object.respApplyConfig)
        : isSet(object.resp_apply_config)
        ? RespApplyConfig.fromJSON(object.resp_apply_config)
        : undefined,
    };
  },

  toJSON(message: WiFiConfigPayload): unknown {
    const obj: any = {};
    if (message.msg !== 0) {
      obj.msg = wiFiConfigMsgTypeToJSON(message.msg);
    }
    if (message.cmdGetStatus !== undefined) {
      obj.cmdGetStatus = CmdGetStatus.toJSON(message.cmdGetStatus);
    }
    if (message.respGetStatus !== undefined) {
      obj.respGetStatus = RespGetStatus.toJSON(message.respGetStatus);
    }
    if (message.cmdSetConfig !== undefined) {
      obj.cmdSetConfig = CmdSetConfig.toJSON(message.cmdSetConfig);
    }
    if (message.respSetConfig !== undefined) {
      obj.respSetConfig = RespSetConfig.toJSON(message.respSetConfig);
    }
    if (message.cmdApplyConfig !== undefined) {
      obj.cmdApplyConfig = CmdApplyConfig.toJSON(message.cmdApplyConfig);
    }
    if (message.respApplyConfig !== undefined) {
      obj.respApplyConfig = RespApplyConfig.toJSON(message.respApplyConfig);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WiFiConfigPayload>, I>>(base?: I): WiFiConfigPayload {
    return WiFiConfigPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WiFiConfigPayload>, I>>(object: I): WiFiConfigPayload {
    const message = createBaseWiFiConfigPayload();
    message.msg = object.msg ?? 0;
    message.cmdGetStatus = (object.cmdGetStatus !== undefined && object.cmdGetStatus !== null)
      ? CmdGetStatus.fromPartial(object.cmdGetStatus)
      : undefined;
    message.respGetStatus = (object.respGetStatus !== undefined && object.respGetStatus !== null)
      ? RespGetStatus.fromPartial(object.respGetStatus)
      : undefined;
    message.cmdSetConfig = (object.cmdSetConfig !== undefined && object.cmdSetConfig !== null)
      ? CmdSetConfig.fromPartial(object.cmdSetConfig)
      : undefined;
    message.respSetConfig = (object.respSetConfig !== undefined && object.respSetConfig !== null)
      ? RespSetConfig.fromPartial(object.respSetConfig)
      : undefined;
    message.cmdApplyConfig = (object.cmdApplyConfig !== undefined && object.cmdApplyConfig !== null)
      ? CmdApplyConfig.fromPartial(object.cmdApplyConfig)
      : undefined;
    message.respApplyConfig = (object.respApplyConfig !== undefined && object.respApplyConfig !== null)
      ? RespApplyConfig.fromPartial(object.respApplyConfig)
      : undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
